#!/usr/bin/env bash
#
# Installer for local_code on Ubuntu/Debian.
#
# Installs build dependencies, builds the binary, and optionally sets up web
# search by running a local SearXNG instance (Docker) configured for JSON API
# access on 127.0.0.1:8888.
#
# Usage: ./install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEARXNG_PORT=8888
SEARXNG_DIR="${SCRIPT_DIR}/searxng"

say()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[warn]\033[0m %s\n' "$*"; }
err()  { printf '\033[31m[error]\033[0m %s\n' "$*" >&2; }

ask_yes() {
  # ask_yes "Prompt" -> returns 0 for yes
  local reply
  read -r -p "$1 [y/N] " reply || true
  [[ "$reply" == "y" || "$reply" == "Y" || "$reply" == "yes" ]]
}

require_apt() {
  if ! command -v apt-get >/dev/null 2>&1; then
    err "This installer targets Ubuntu/Debian (apt-get not found)."
    err "Install the deps manually: build-essential cmake libcurl4-openssl-dev libncurses-dev"
    exit 1
  fi
}

# --- 1. Build dependencies --------------------------------------------------
install_build_deps() {
  say "Installing build dependencies (sudo apt-get)..."
  sudo apt-get update -y
  sudo apt-get install -y build-essential cmake git curl \
       libcurl4-openssl-dev libncurses-dev
}

# --- 2. Build ---------------------------------------------------------------
build_app() {
  say "Building local_code..."
  cmake -S "$SCRIPT_DIR" -B "$SCRIPT_DIR/build"
  cmake --build "$SCRIPT_DIR/build" -j
  say "Built: $SCRIPT_DIR/build/local_code"
}

# --- 3. Optional: SearXNG for web search ------------------------------------
ensure_docker() {
  if command -v docker >/dev/null 2>&1; then return 0; fi
  say "Docker not found; installing docker.io..."
  sudo apt-get install -y docker.io
  sudo systemctl enable --now docker
  if ! getent group docker | grep -q "\b${USER}\b"; then
    sudo usermod -aG docker "$USER" || true
    warn "Added $USER to the 'docker' group — log out/in for non-sudo docker."
  fi
}

write_searxng_settings() {
  mkdir -p "$SEARXNG_DIR"
  local secret
  if command -v openssl >/dev/null 2>&1; then
    secret="$(openssl rand -hex 32)"
  else
    secret="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi
  cat > "$SEARXNG_DIR/settings.yml" <<YAML
# Generated by local_code/install.sh
use_default_settings: true
server:
  secret_key: "${secret}"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
search:
  formats:
    - html
    - json
YAML
  say "Wrote $SEARXNG_DIR/settings.yml (JSON API enabled)."
}

setup_searxng() {
  ensure_docker
  write_searxng_settings

  say "Starting SearXNG container on 127.0.0.1:${SEARXNG_PORT}..."
  sudo docker rm -f searxng >/dev/null 2>&1 || true
  sudo docker run -d --name searxng --restart unless-stopped \
    -p "127.0.0.1:${SEARXNG_PORT}:8080" \
    -v "${SEARXNG_DIR}:/etc/searxng" \
    searxng/searxng:latest

  say "Waiting for SearXNG to come up..."
  local ok=0
  for _ in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:${SEARXNG_PORT}/search?q=test&format=json" \
         -A local_code/1.0 >/dev/null 2>&1; then
      ok=1; break
    fi
    sleep 1
  done
  if [[ "$ok" == "1" ]]; then
    say "SearXNG JSON API is up at http://127.0.0.1:${SEARXNG_PORT}"
  else
    warn "SearXNG did not answer the JSON API in time."
    warn "Check: sudo docker logs searxng"
  fi
}

# --- main -------------------------------------------------------------------
main() {
  require_apt
  install_build_deps
  build_app

  echo
  if ask_yes "Enable web search via a local SearXNG server (installs Docker if needed)?"; then
    setup_searxng
  else
    say "Skipping web search. You can re-run this script later to enable it."
  fi

  echo
  say "Done. Run it with:"
  echo "    $SCRIPT_DIR/build/local_code"
  echo
  echo "Notes:"
  echo "  - Requires Ollama running locally (https://ollama.com)."
  echo "  - Web search auto-detects SearXNG at http://localhost:${SEARXNG_PORT}"
  echo "    (override with --searxng URL; disable with --no-web)."
}

main "$@"
